# The URL the site will be built for
base_url = "/clop/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Syntax highlighting is disabled by default

[extra]
# Site info
title = "CLOP"
description = "Count Command Line OPtions"
author = "Xhevahire Tërnava"
